# Generated by Django 5.0.4 on 2024-05-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
