# Generated by Django 5.0.4 on 2024-04-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('apellido', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
