# Generated by Django 5.0.4 on 2024-05-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={},
        ),
        migrations.AlterField(
            model_name='about',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
    ]
