# Generated by Django 5.0.4 on 2024-05-12 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_options_alter_about_descripcion'),
        ('about', '0002_alter_about_options_alter_about_descripcion(1)'),
    ]

    operations = [
    ]
