# Generated by Django 5.0.4 on 2024-05-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_merge_20240511_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagen_about'),
        ),
    ]
