verse = "un verso en 2323 una Cadena"

x = verse.upper()
print(x)
x = verse.capitalize()
print(x)
x = verse.lower()
print(x)
x = verse.title()
print(x)
x = verse.replace("er", "3")
print(x)
x = verse.split()
x = " ".join(["es", "un", "verso"])
print(x)